function [sosMatrix,ScaleValues] = LP
%LP Returns a discrete-time filter object sosMatriz and Scalevalues.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
%
% Generated on: 27-Apr-2014 20:29:59
%

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
Fs = 8192;  % Sampling Frequency

Fpass = 2000;        % Passband Frequency
Fstop = 3000;        % Stopband Frequency
Apass = 1;           % Passband Ripple (dB)
Astop = 80;          % Stopband Attenuation (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

sosMatrix = Hd.sosMatrix;
ScaleValues = Hd.ScaleValues;
